### ISSUE TITLE
bower.json

### ISSUE THREAD

**Issue by HawkeyePierce89** [scurker/currency.js#108]
```
  "main": [
    "dist/currency.js"
  ],
```

but dist-folder is missing

![image](https://user-images.githubusercontent.com/25603805/38863650-81f88864-4262-11e8-8644-018aea87ed85.png)

**Comment by scurker** [comment]
I'm a little bit conflicted here as this has apparently been broken since `v1.0.0`. Given that bower itself is only lightly maintained, the best options seem to be either to migrate to using npm/yarn or using [bower-npm-resolver](https://www.npmjs.com/package/bower-npm-resolver) if you can't migrate at this time.

> .bowerrc
```javascript
{
  "resolvers": [
    "bower-npm-resolver"
  ]
}
```

> bower.json
```javascript
{
  "dependencies": {
    "currency.js": "npm:currency.js#~1.0.0"
  }
}
```

**Comment by voondo** [comment]
Thanks for the solution ! Maybe you could remove the package from the bower registry (or stick with < v1.0.0) ? 
I have some legacy apps which still rely on bower and I guess I'm not alone ;)

**Comment by scurker** [comment]
I really need to deprecate the `bower.json` file, and that would've been a good solution for the `1.0.0` release. Unfortunately, it does not seem you can unpublish existing bower versions so I'm trying to determine what a good path going forward would be.

**Comment by giorgiobeggiora** [comment]
news about this?
