### ISSUE TITLE
IEEE754 bug appears at extreme precision values

### ISSUE THREAD

**Issue by miltonhowe** [scurker/currency.js#121]
I received the following results when using `precision` of 18 or greater.
![image](https://user-images.githubusercontent.com/414414/40793720-2e60e62a-64cb-11e8-907c-c8bb093d1741.png)

![image](https://user-images.githubusercontent.com/414414/40793747-436a0358-64cb-11e8-984d-3e4412b95385.png)

This is obviously an extreme example which would be unlikely to cause problems in most real life scenarios, but it is a bug nonetheless.

my code:
```
this.settlement.total = currency(this.settlement.amount, {precision: 18}).multiply((currency(1, {precision: 18}).add((currency(this.settlement.feePercent, {precision: 18}).divide(100))))).value;
```

**Comment by scurker** [comment]
It's kind of a bug, but not really if you understand the limitations of IEEE 754. Since currency stores values internally as integers, numbers are only safe below 2<sup>53</sup> in cents or  `Number.MAX_SAFE_INTEGER`. Since you're specifying a precision of 18, it's never guaranteed to be safe since the precise number of digits will always exceed 2<sup>53</sup>. Currency was never originally planned to solve for issues beyond the signed 32 bit integer limit.

#8 is for handling a warning if that value is exceeded, but it hasn't been implemented yet.

If you really need that kind of precision with currencies, there's a [couple](https://github.com/MikeMcl/bignumber.js/) [of](https://github.com/indutny/bn.js/) [other](https://github.com/peterolson/BigInteger.js) libraries that might be better suited to your needs. Otherwise, [BigInt](https://developers.google.com/web/updates/2018/05/bigint) is coming in the near future to better handle arbitrary precision.
