### ISSUE TITLE
Can't format big numbers.

### ISSUE THREAD

**Issue by WALNUTZGAMING** [scurker/currency.js#147]
Example the number is '2.443233038698408e+21' and what currency.js does when currency('2.443233038698408e+21').format() the result is '2.44', that's not the correct answer!

![3](https://user-images.githubusercontent.com/38658663/45915190-96839880-be83-11e8-95a7-8c6e9cb535d0.PNG)

**Comment by scurker** [comment]
At the moment, this is expected. currency.js doesn't handle scientific notation, and since it uses Integers behind the scene, there's a limitation of `Number.MAX_SAFE_INTEGER`. 

If you need to handle larger numbers (or larger currencies) [BigNumber](https://github.com/MikeMcl/bignumber.js/) may be a safer bet. If for whatever reason you have a number that is less than `Number.MAX_SAFE_INTEGER` and is in scientific notation, you can parse as a number before passing it into currency.js, i.e. `currency(Number('1.23e+5'))`.
