### ISSUE TITLE
Why not use float?

### ISSUE THREAD

**Issue by evert** [scurker/currency.js#167]
This is a legitimate question. I'm doing research on financial math, and I don't really understand why you're using integers, when you can use floating point numbers.

Yes, floating point numbers are not guaranteed to be exact, but integers also have limitations. Since you tend to default to a precision of 2 digits, I can't think of a (reasonable size) calculation where you can just use a floating point number and round with `toFixed()` for display.

I hope this is not taken as a criticism, I'm just trying to learn. I wrote some notes [on my blog](https://evertpot.com/currencies-floats/) but I would love to understand if I'm incorrect.

**Comment by tmorehouse** [comment]
I would say it is because of math. To keep precision.

**Comment by evert** [comment]
@tmorehouse , I realize you're not the author of the package, but do you know of example where using floats and `toFixed()` does not work?

**Comment by tmorehouse** [comment]
Some fixed point numbers (specifically the fractional portion) cannot be stored in binary floats without issues.

Take for example:
```js
a = 0.1 // => 0.1
b = 0.2 // => 0.2
a + b   // => 0.30000000000000004
```
Over numerous computations this error can grow larger and larger when doing currency math.

A good article on Javascript and currecy is https://frontstuff.io/how-to-handle-monetary-values-in-javascript

> Using a decimal system has advantages, but raises a major issue when it comes to programming. Computers use a binary system, so they can’t natively represent decimal numbers. Some languages have come up with their own solutions like the `BigDecimal` type in Java or the `decimal` type in C#. JavaScript only has the `Number` type, which can be used as an integer or a double precision float. Because it’s a binary representation of a base 10 system, you end up with inaccurate results when you try to do math.
> Using floats to store monetary values is a bad idea. As you calculate more values, the imperceptible precision errors lead to larger gaps. This inevitably ends up causing rounding issues.

**Comment by evert** [comment]
Hi @tmorehouse ,

Your example makes sense for calculations where very small fractions are relevant, but this library only cares about 2 digits for USD, so the problem with floating point rounding errors become pretty much irrelevant.

The rounding error for using only 2 digits is much higher than the rounding error from using floating-point math. Consider your example:

```javascript
a = 0.1 // => 0.1
b = 0.2 // => 0.2
(a + b).toFixed(2)   // => 0.30
```

But this example is a little unfair. Lets consider an example where we care actually care about precision. Compounding interest might be an example, but it's easier to break down.

```javascript
> currency(10).divide(3).multiply(3).format();
'9.99'
```

```javascript
> 10/3*3
10
```

It's very easy to proof that using floating points is _much_ more precise that using currency.js. This is true for most reasonable values in finance, unless you get to absurdly high amounts.

I 100% understand that using BigInt is better for financial math, but if you only keep 2 digits it is _less_ accurate than using floating points. What am I missing?

**Comment by evert** [comment]
Worth noting that financial systems use a LOT more digits than 2. For those cases I agree, it might be better to use fixed-point math over floating-point math, it's just not true when dealing with only 2 digits.

**Comment by scurker** [comment]
This is a great question! I'll try to summarize as best I can. 

Integers (or some other representation such as Decimals, or BigNumber) always have 100% precision. There is no precision loss outside of the limitations of `Number.MAX_SAFE_INTEGER` if you're using integers; other methods may have other restrictions. If currencies always had an exact precision of 2, you would be correct that `toFixed(2)` likely would work in those cases.

Unfortunately, currencies don't always end up with a precise number and that's where things can start to cause trouble. Taxes and other percentage calculations happen with a result that ends up with a number less than `.01`, so we have to decide how to round. Since a floating point number can end up higher or lower than the real value, using `toFixed(2)` can actually round in the wrong direction, leading to missing or added cents.

Let me explain with an example:

```
(17.955).toFixed(2); // => "17.95"
(17.954 + .001).toFixed(2); // => "17.96"
```

Both numbers should be exactly the same (`17.955`), but they actually aren't in reality since floating point precision can't accurately store every decimal number. Sometimes the same number can be rounded up, or rounded down depending on how that number was eventually reached. If the number beyond the precision is `.004999999~` or less, it'll round down to `.00`. If it's larger than that it'll round up. It doesn't really matter where that number is, so even a number as small as `.00000000000000001` can cause the final precision to be off by a cent if it's on the wrong side of the half cent.

And while the default precision is `2`, the precision doesn't really matter since we deal in integers. We can safely deal in whatever precision you would like (again up to `Number.MAX_SAFE_INTEGER`).

**Comment by evert** [comment]
Hi @scurker ,

Thanks for the answer. This makes a lot of sense. Basically what I'm understanding from this really comes down to one thing: by using floating points it becomes possible for rounding to be slightly off. Would that correctly summarize it?

**Comment by scurker** [comment]
Correct, you shouldn't ever be off by more than a cent (or whatever the least significant digit of your chosen precision is). Those cents can eventually add up depending on the number of different calculations you do.

I did want to address one of your examples above:

```
> currency(10).divide(3).multiply(3).format();
'9.99'
```

I wouldn't qualify this as a precision error, but it is still in fact a precision loss. In terms of currency, there's no way to accurately represent this. This is taken into account with `distribute`, in that any remainder cents have to go somewhere:

```
> currency(10).distribute(3);
[3.33, 3.33, 3.34]
```

**Comment by evert** [comment]
Thanks again @scurker =)

**Comment by evert** [comment]
So I _reeeally_ went down the rabbit hole with this and implementing a money object using the new Ecmascript bigint type.

Anyway, an interesting detail I found was that the example you gave:

    (17.954 + .001).toFixed(2); // => "17.96"

Probably actually rounds correctly. I found out about 'bankers rounding' (otherwise also known as round half to nearest even) and the implications are that:

    0.035 -> should round to 0.04
    0.045 -> should round to 0.04
    0.055 -> should round to 0.06

Not sure if this is interesting for this project. I found it pretty difficult to implement, but eventually got it done. This is (so far) the result of my work: https://github.com/evert/bigint-money/ You helped with getting me to understand a key part. Thank you!

**Comment by scurker** [comment]
Glad I could help!

In the example I mentioned `17.955`, will round up or down dependent on the fractional value so it's not consistent in its rounding if you rely on just floating point. For currency.js, we adhere to [half up](https://en.wikipedia.org/wiki/Rounding#Round_half_up) rounding, but banker's rounding is another alternative depending on your uses.

**Comment by evert** [comment]
Yea, sorry. My comment wasn't meant as an a pro-float argument ;) . I just ran into this because I wanted to incorporate your specific example in my unittests. It failed because I do use bankers-rounding, because half-up rounding introduces a bias to round numbers up and i thought you might find that interesting.
