### ISSUE TITLE
.multiply Bug

### ISSUE THREAD

**Issue by Raptor2277** [scurker/currency.js#186]
When doing currency(x).multiply(y), if y is a string that cannot be "parsed inline by JS" it will always return NaN.

What I mean by "parsed inline by JS" is that if you type 3 * "3000" in console it will work. However 3 * "3,000" will return NaN.

I consider this a bug because .subtract .divide and .add will work with all strings because those methods use your internal parse function. This leads users to believe all methods will work when that is not the case.

I suggest you add parsing to the .multiply function.

**Comment by scurker** [comment]
Currently, `.multiply()` expects a decimal value since currencies are commonly multiplied by higher precision values, such in the case of tax. I do agree that it doesn't necessarily match the signature of the other arithmetic methods, but it's intentional at the moment. It's currently documented as `number` in typescript and the documentation, although the jsdoc is ambiguous. At a minimum, the jsdoc should probably be updated to reflect the current params.

For the other cases, if `.multiply()` were to accept any value (`currency`, `string`, or `number`) there's a lot of edge cases to consider. All of the parse logic currently takes into account the internal precision of the currency so `currency(123).multiply(0.0125)` would return different results than `currency(123).multiply("0.0125")`.
