### ISSUE TITLE
currency(100000.00) >= currency(14000) returns false

### ISSUE THREAD

**Issue by tarunguddeti** [scurker/currency.js#246]

**Comment by scurker** [comment]
This is expected because currency returns an object (or string) depending on how it's evaluated.

```js
typeof currency(100000.00); // "object"
currency(1000) === currency(1000); // false
currency(1.23) + currency(4.56); // "1.234.56"
```

For comparisons, you need to use `.value` or `.intValue` to get the actual number.

```js
currency(100000.00).value >= currency(14000).value; // true
currency(100000.00).value <= currency(14000).value; // false
```

Alternatively, there's a [currency babel plugin](https://github.com/scurker/babel-plugin-transform-currency-operators) that will handle this for you.
