### ISSUE TITLE
Npm 2.0.4 doesn't match src/currency.js

### ISSUE THREAD

**Issue by mgatto** [scurker/currency.js#453]
`src/currency.js` uses ES6 const and so forth while version 2.0.4 on npm reverts to `var` and other code differences. Which one is authoritative, when both have been current for 2-3 years? Should npm be updated?

**Comment by scurker** [comment]
This is intentional. The package that gets shipped in npm is transpiled from the source code and both an [es module](https://unpkg.com/browse/currency.js@2.0.4/dist/currency.es.js) and a [common js module](https://unpkg.com/browse/currency.js@2.0.4/dist/currency.js) are both included in the npm package. Bundlers will typically pick the correct one based on package.json metadata.
