### ISSUE TITLE
Support for Indian numbering system

### ISSUE THREAD

**Issue by hameedraha** [scurker/currency.js#74]
Option to specify grouping/numbering system.

Please refer: https://en.wikipedia.org/wiki/Indian_numbering_system

**Comment by scurker** [comment]
Hi @hameedraha, thanks for the suggestion! I could use use a little help as I'm not familiar with the Indian numbering system. I've taken a stab with 80988ba. Currently, this looks like:

```js
import currency from 'currency.js';

currency(1234567.89, { useVedic: true }).format(); // => '12,34,567.89'
```

Since I'm not familiar with this system, I don't know how it's typically referred to. This method of formatting large numbers seems to be common through various regions of South Asia so I want to make sure the option is accessible to those who would use it. Is vedic numbering generally understood or is there a more common term?
